name: 'Deploy to environment'
description: 'Deploys the artifact to the hosted environment'
inputs:
  - azure-publish-profile:
    required: true
  - artifact-name:
    required: true
  - azure-webapp-name:
    required: true
runs:
  using: "composite"
  steps:

      - name: Download Publish Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact-name}}
  
      - uses: azure/webapps-deploy@v2
        name: Deploy
        with:
          app-name: ${{inputs.azure-webapp-name}}
          publish-profile: ${{inputs.azure-publish-profile}}
          package: .
