name: 'Deploy to environment'
description: 'Deploys the a'
runs:
  using: "composite"
  steps:

      - name: Download Publish Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{env.API_PROJECT_NAME}}
  
      - uses: azure/webapps-deploy@v2
        name: Deploy
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .
