name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.x' # The .NET SDK version to use
  API_PROJECT_NAME: 'Explorations.Pipelines.Api'
  PUBLISH_OUTPUT_FOLDER: 'publish-output'

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v4
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Publish
        run: dotnet publish '${{env.API_PROJECT_NAME}}/${{env.API_PROJECT_NAME}}.csproj' -c Release -o '${{env.PUBLISH_OUTPUT_FOLDER}}'
      - name: Upload Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.API_PROJECT_NAME}}
          path: ${{env.PUBLISH_OUTPUT_FOLDER}}

  staging:
    needs: publish
    environment: Staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          azure-publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          artifact-name: ${{env.API_PROJECT_NAME}}
          azure-webapp-name: ${{ env.AZURE_WEBAPP_NAME }}

  production:
    needs: staging
    environment: Production
    runs-on: ubuntu-latest

    steps:
    - name: Download Publish Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{env.API_ARTIFACT_NAME}}

        


    - run: echo "$PWD" 
    - run: ls -LR
    
