name: publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: ExplorationsPipelinesApi
  AZURE_WEBAPP_PACKAGE_PATH: '.' # Set this to the path to your web app project, defaults to the repository root:
  DOTNET_VERSION: '8.0.x' # The .NET SDK version to use
  API_PROJECT_NAME: 'Explorations.Pipelines.Api'
  PUBLISH_OUTPUT_FOLDER: 'publish-output'

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - run: echo '${{ toJson(github) }}'
      - run: dir 
      - run: echo "API_ARTIFACT_NAME=${{env.API_PROJECT_NAME}}-${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
    
      - uses: actions/checkout@v3
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - run: cd ${{env.API_PROJECT_NAME}}

      - name: Install dependencies
        run: dotnet restore '${{env.API_PROJECT_NAME}}.csproj'

      - name: Build
        run: dotnet build --configuration Release --no-restore '${{env.API_PROJECT_NAME}}.csproj'
          
      - name: Publish
        run: dotnet publish -c Release -o '../${{env.PUBLISH_OUTPUT_FOLDER}}' -r linux-x64 --self-contained true /p:UseAppHost=true '${{env.API_PROJECT_NAME}}.csproj'

      - name: Upload Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.API_ARTIFACT_NAME}}
          path: '../${{env.PUBLISH_OUTPUT_FOLDER}}'

  staging:
    needs: publish
    runs-on: ubuntu-latest

    steps:
    - name: Download Publish Artifact
      uses: actions//download-artifact@v4
      with:
        name: ${{env.API_ARTIFACT_NAME}}
      
    
